name: Runic

on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "docs/make.jl"
      - ".github/workflows/Runic.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  runic:
    name: Runic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fredrikekre/runic-action@v1
        with:
          version: "1"
